/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchatsRouteImport } from './routes/_authenticated/achats'
import { Route as AuthenticatedAlertesRouteImport } from './routes/_authenticated/alertes'
import { Route as AuthenticatedCaissesRouteImport } from './routes/_authenticated/caisses'
import { Route as AuthenticatedComptabiliteRouteImport } from './routes/_authenticated/comptabilite'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDonneesRouteImport } from './routes/_authenticated/donnees'
import { Route as AuthenticatedMaterielRouteImport } from './routes/_authenticated/materiel'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/personnel'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated/ventes'
import { Route as AuthenticatedAchatsIndexRouteImport } from './routes/_authenticated/achats.index'
import { Route as AuthenticatedAchatsAnalyseRouteImport } from './routes/_authenticated/achats.analyse'
import { Route as AuthenticatedAchatsAvoirsRouteImport } from './routes/_authenticated/achats.avoirs'
import { Route as AuthenticatedAchatsDemandesRouteImport } from './routes/_authenticated/achats.demandes'
import { Route as AuthenticatedAchatsFacturesRouteImport } from './routes/_authenticated/achats.factures'
import { Route as AuthenticatedAchatsReceptionsRouteImport } from './routes/_authenticated/achats.receptions'
import { Route as AuthenticatedAchatsReglementsRouteImport } from './routes/_authenticated/achats.reglements'
import { Route as AuthenticatedAchatsRetoursRouteImport } from './routes/_authenticated/achats.retours'
import { Route as AuthenticatedCaissesIndexRouteImport } from './routes/_authenticated/caisses.index'
import { Route as AuthenticatedCaissesAlimentationsRouteImport } from './routes/_authenticated/caisses.alimentations'
import { Route as AuthenticatedCaissesAnalyseRouteImport } from './routes/_authenticated/caisses.analyse'
import { Route as AuthenticatedCaissesDepensesRouteImport } from './routes/_authenticated/caisses.depenses'
import { Route as AuthenticatedComptabiliteIndexRouteImport } from './routes/_authenticated/comptabilite.index'
import { Route as AuthenticatedComptabiliteBalanceRouteImport } from './routes/_authenticated/comptabilite.balance'
import { Route as AuthenticatedComptabiliteEcrituresRouteImport } from './routes/_authenticated/comptabilite.ecritures'
import { Route as AuthenticatedComptabiliteEtatsRouteImport } from './routes/_authenticated/comptabilite.etats'
import { Route as AuthenticatedComptabiliteGrandLivreRouteImport } from './routes/_authenticated/comptabilite.grand-livre'
import { Route as AuthenticatedComptabiliteJournauxRouteImport } from './routes/_authenticated/comptabilite.journaux'
import { Route as AuthenticatedComptabilitePlanRouteImport } from './routes/_authenticated/comptabilite.plan'
import { Route as AuthenticatedComptabiliteRapprochementRouteImport } from './routes/_authenticated/comptabilite.rapprochement'
import { Route as AuthenticatedDonneesIndexRouteImport } from './routes/_authenticated/donnees.index'
import { Route as AuthenticatedDonneesClientsRouteImport } from './routes/_authenticated/donnees.clients'
import { Route as AuthenticatedDonneesConstituantsRouteImport } from './routes/_authenticated/donnees.constituants'
import { Route as AuthenticatedDonneesDepotsRouteImport } from './routes/_authenticated/donnees.depots'
import { Route as AuthenticatedDonneesFournisseursRouteImport } from './routes/_authenticated/donnees.fournisseurs'
import { Route as AuthenticatedDonneesLogRouteImport } from './routes/_authenticated/donnees.log'
import { Route as AuthenticatedDonneesParametresRouteImport } from './routes/_authenticated/donnees.parametres'
import { Route as AuthenticatedDonneesProduitsRouteImport } from './routes/_authenticated/donnees.produits'
import { Route as AuthenticatedDonneesSocieteRouteImport } from './routes/_authenticated/donnees.societe'
import { Route as AuthenticatedDonneesUtilisateursRouteImport } from './routes/_authenticated/donnees.utilisateurs'
import { Route as AuthenticatedMaterielIndexRouteImport } from './routes/_authenticated/materiel.index'
import { Route as AuthenticatedMaterielAnalyseRouteImport } from './routes/_authenticated/materiel.analyse'
import { Route as AuthenticatedMaterielDocumentsRouteImport } from './routes/_authenticated/materiel.documents'
import { Route as AuthenticatedMaterielEntretiensRouteImport } from './routes/_authenticated/materiel.entretiens'
import { Route as AuthenticatedMaterielGasoilRouteImport } from './routes/_authenticated/materiel.gasoil'
import { Route as AuthenticatedMaterielLocationsRouteImport } from './routes/_authenticated/materiel.locations'
import { Route as AuthenticatedMaterielPannesRouteImport } from './routes/_authenticated/materiel.pannes'
import { Route as AuthenticatedMaterielPapiersRouteImport } from './routes/_authenticated/materiel.papiers'
import { Route as AuthenticatedMaterielPeriodiquesRouteImport } from './routes/_authenticated/materiel.periodiques'
import { Route as AuthenticatedMaterielTransfertsRouteImport } from './routes/_authenticated/materiel.transferts'
import { Route as AuthenticatedPersonnelIndexRouteImport } from './routes/_authenticated/personnel.index'
import { Route as AuthenticatedPersonnelAbsencesRouteImport } from './routes/_authenticated/personnel.absences'
import { Route as AuthenticatedPersonnelAnalyseRouteImport } from './routes/_authenticated/personnel.analyse'
import { Route as AuthenticatedPersonnelAvancesRouteImport } from './routes/_authenticated/personnel.avances'
import { Route as AuthenticatedPersonnelCongesRouteImport } from './routes/_authenticated/personnel.conges'
import { Route as AuthenticatedPersonnelPaieRouteImport } from './routes/_authenticated/personnel.paie'
import { Route as AuthenticatedPersonnelPointageRouteImport } from './routes/_authenticated/personnel.pointage'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production.index'
import { Route as AuthenticatedProductionAnalyseRouteImport } from './routes/_authenticated/production.analyse'
import { Route as AuthenticatedProductionConsommationRouteImport } from './routes/_authenticated/production.consommation'
import { Route as AuthenticatedProductionPhasesRouteImport } from './routes/_authenticated/production.phases'
import { Route as AuthenticatedProductionRendementRouteImport } from './routes/_authenticated/production.rendement'
import { Route as AuthenticatedProductionSoustraitanceRouteImport } from './routes/_authenticated/production.soustraitance'
import { Route as AuthenticatedProductionSoustraitanceAuditRouteImport } from './routes/_authenticated/production.soustraitance-audit'
import { Route as AuthenticatedProductionTachesRouteImport } from './routes/_authenticated/production.taches'
import { Route as AuthenticatedStocksIndexRouteImport } from './routes/_authenticated/stocks.index'
import { Route as AuthenticatedStocksAnalyseRouteImport } from './routes/_authenticated/stocks.analyse'
import { Route as AuthenticatedStocksInventaireRouteImport } from './routes/_authenticated/stocks.inventaire'
import { Route as AuthenticatedStocksTransfertsRouteImport } from './routes/_authenticated/stocks.transferts'
import { Route as AuthenticatedTransportIndexRouteImport } from './routes/_authenticated/transport.index'
import { Route as AuthenticatedTransportAnalyseRouteImport } from './routes/_authenticated/transport.analyse'
import { Route as AuthenticatedTransportSuiviRouteImport } from './routes/_authenticated/transport.suivi'
import { Route as AuthenticatedVentesIndexRouteImport } from './routes/_authenticated/ventes.index'
import { Route as AuthenticatedVentesAnalyseRouteImport } from './routes/_authenticated/ventes.analyse'
import { Route as AuthenticatedVentesAvoirsRouteImport } from './routes/_authenticated/ventes.avoirs'
import { Route as AuthenticatedVentesCommandesRouteImport } from './routes/_authenticated/ventes.commandes'
import { Route as AuthenticatedVentesDevisRouteImport } from './routes/_authenticated/ventes.devis'
import { Route as AuthenticatedVentesFacturesRouteImport } from './routes/_authenticated/ventes.factures'
import { Route as AuthenticatedVentesLivraisonsRouteImport } from './routes/_authenticated/ventes.livraisons'
import { Route as AuthenticatedVentesReglementsRouteImport } from './routes/_authenticated/ventes.reglements'
import { Route as AuthenticatedVentesRetoursRouteImport } from './routes/_authenticated/ventes.retours'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchatsRoute = AuthenticatedAchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertesRoute = AuthenticatedAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaissesRoute = AuthenticatedCaissesRouteImport.update({
  id: '/caisses',
  path: '/caisses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComptabiliteRoute =
  AuthenticatedComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonneesRoute = AuthenticatedDonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterielRoute = AuthenticatedMaterielRouteImport.update({
  id: '/materiel',
  path: '/materiel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchatsIndexRoute =
  AuthenticatedAchatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsAnalyseRoute =
  AuthenticatedAchatsAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsAvoirsRoute =
  AuthenticatedAchatsAvoirsRouteImport.update({
    id: '/avoirs',
    path: '/avoirs',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsDemandesRoute =
  AuthenticatedAchatsDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsFacturesRoute =
  AuthenticatedAchatsFacturesRouteImport.update({
    id: '/factures',
    path: '/factures',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsReceptionsRoute =
  AuthenticatedAchatsReceptionsRouteImport.update({
    id: '/receptions',
    path: '/receptions',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsReglementsRoute =
  AuthenticatedAchatsReglementsRouteImport.update({
    id: '/reglements',
    path: '/reglements',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedAchatsRetoursRoute =
  AuthenticatedAchatsRetoursRouteImport.update({
    id: '/retours',
    path: '/retours',
    getParentRoute: () => AuthenticatedAchatsRoute,
  } as any)
const AuthenticatedCaissesIndexRoute =
  AuthenticatedCaissesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCaissesRoute,
  } as any)
const AuthenticatedCaissesAlimentationsRoute =
  AuthenticatedCaissesAlimentationsRouteImport.update({
    id: '/alimentations',
    path: '/alimentations',
    getParentRoute: () => AuthenticatedCaissesRoute,
  } as any)
const AuthenticatedCaissesAnalyseRoute =
  AuthenticatedCaissesAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedCaissesRoute,
  } as any)
const AuthenticatedCaissesDepensesRoute =
  AuthenticatedCaissesDepensesRouteImport.update({
    id: '/depenses',
    path: '/depenses',
    getParentRoute: () => AuthenticatedCaissesRoute,
  } as any)
const AuthenticatedComptabiliteIndexRoute =
  AuthenticatedComptabiliteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteBalanceRoute =
  AuthenticatedComptabiliteBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteEcrituresRoute =
  AuthenticatedComptabiliteEcrituresRouteImport.update({
    id: '/ecritures',
    path: '/ecritures',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteEtatsRoute =
  AuthenticatedComptabiliteEtatsRouteImport.update({
    id: '/etats',
    path: '/etats',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteGrandLivreRoute =
  AuthenticatedComptabiliteGrandLivreRouteImport.update({
    id: '/grand-livre',
    path: '/grand-livre',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteJournauxRoute =
  AuthenticatedComptabiliteJournauxRouteImport.update({
    id: '/journaux',
    path: '/journaux',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabilitePlanRoute =
  AuthenticatedComptabilitePlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteRapprochementRoute =
  AuthenticatedComptabiliteRapprochementRouteImport.update({
    id: '/rapprochement',
    path: '/rapprochement',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedDonneesIndexRoute =
  AuthenticatedDonneesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesClientsRoute =
  AuthenticatedDonneesClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesConstituantsRoute =
  AuthenticatedDonneesConstituantsRouteImport.update({
    id: '/constituants',
    path: '/constituants',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesDepotsRoute =
  AuthenticatedDonneesDepotsRouteImport.update({
    id: '/depots',
    path: '/depots',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesFournisseursRoute =
  AuthenticatedDonneesFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesLogRoute = AuthenticatedDonneesLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedDonneesRoute,
} as any)
const AuthenticatedDonneesParametresRoute =
  AuthenticatedDonneesParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesProduitsRoute =
  AuthenticatedDonneesProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesSocieteRoute =
  AuthenticatedDonneesSocieteRouteImport.update({
    id: '/societe',
    path: '/societe',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedDonneesUtilisateursRoute =
  AuthenticatedDonneesUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedDonneesRoute,
  } as any)
const AuthenticatedMaterielIndexRoute =
  AuthenticatedMaterielIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielAnalyseRoute =
  AuthenticatedMaterielAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielDocumentsRoute =
  AuthenticatedMaterielDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielEntretiensRoute =
  AuthenticatedMaterielEntretiensRouteImport.update({
    id: '/entretiens',
    path: '/entretiens',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielGasoilRoute =
  AuthenticatedMaterielGasoilRouteImport.update({
    id: '/gasoil',
    path: '/gasoil',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielLocationsRoute =
  AuthenticatedMaterielLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielPannesRoute =
  AuthenticatedMaterielPannesRouteImport.update({
    id: '/pannes',
    path: '/pannes',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielPapiersRoute =
  AuthenticatedMaterielPapiersRouteImport.update({
    id: '/papiers',
    path: '/papiers',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielPeriodiquesRoute =
  AuthenticatedMaterielPeriodiquesRouteImport.update({
    id: '/periodiques',
    path: '/periodiques',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedMaterielTransfertsRoute =
  AuthenticatedMaterielTransfertsRouteImport.update({
    id: '/transferts',
    path: '/transferts',
    getParentRoute: () => AuthenticatedMaterielRoute,
  } as any)
const AuthenticatedPersonnelIndexRoute =
  AuthenticatedPersonnelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelAbsencesRoute =
  AuthenticatedPersonnelAbsencesRouteImport.update({
    id: '/absences',
    path: '/absences',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelAnalyseRoute =
  AuthenticatedPersonnelAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelAvancesRoute =
  AuthenticatedPersonnelAvancesRouteImport.update({
    id: '/avances',
    path: '/avances',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelCongesRoute =
  AuthenticatedPersonnelCongesRouteImport.update({
    id: '/conges',
    path: '/conges',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelPaieRoute =
  AuthenticatedPersonnelPaieRouteImport.update({
    id: '/paie',
    path: '/paie',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelPointageRoute =
  AuthenticatedPersonnelPointageRouteImport.update({
    id: '/pointage',
    path: '/pointage',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionAnalyseRoute =
  AuthenticatedProductionAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionConsommationRoute =
  AuthenticatedProductionConsommationRouteImport.update({
    id: '/consommation',
    path: '/consommation',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionPhasesRoute =
  AuthenticatedProductionPhasesRouteImport.update({
    id: '/phases',
    path: '/phases',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionRendementRoute =
  AuthenticatedProductionRendementRouteImport.update({
    id: '/rendement',
    path: '/rendement',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionSoustraitanceRoute =
  AuthenticatedProductionSoustraitanceRouteImport.update({
    id: '/soustraitance',
    path: '/soustraitance',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionSoustraitanceAuditRoute =
  AuthenticatedProductionSoustraitanceAuditRouteImport.update({
    id: '/soustraitance-audit',
    path: '/soustraitance-audit',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionTachesRoute =
  AuthenticatedProductionTachesRouteImport.update({
    id: '/taches',
    path: '/taches',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedStocksIndexRoute =
  AuthenticatedStocksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStocksRoute,
  } as any)
const AuthenticatedStocksAnalyseRoute =
  AuthenticatedStocksAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedStocksRoute,
  } as any)
const AuthenticatedStocksInventaireRoute =
  AuthenticatedStocksInventaireRouteImport.update({
    id: '/inventaire',
    path: '/inventaire',
    getParentRoute: () => AuthenticatedStocksRoute,
  } as any)
const AuthenticatedStocksTransfertsRoute =
  AuthenticatedStocksTransfertsRouteImport.update({
    id: '/transferts',
    path: '/transferts',
    getParentRoute: () => AuthenticatedStocksRoute,
  } as any)
const AuthenticatedTransportIndexRoute =
  AuthenticatedTransportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransportRoute,
  } as any)
const AuthenticatedTransportAnalyseRoute =
  AuthenticatedTransportAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedTransportRoute,
  } as any)
const AuthenticatedTransportSuiviRoute =
  AuthenticatedTransportSuiviRouteImport.update({
    id: '/suivi',
    path: '/suivi',
    getParentRoute: () => AuthenticatedTransportRoute,
  } as any)
const AuthenticatedVentesIndexRoute =
  AuthenticatedVentesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesAnalyseRoute =
  AuthenticatedVentesAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesAvoirsRoute =
  AuthenticatedVentesAvoirsRouteImport.update({
    id: '/avoirs',
    path: '/avoirs',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesCommandesRoute =
  AuthenticatedVentesCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesDevisRoute =
  AuthenticatedVentesDevisRouteImport.update({
    id: '/devis',
    path: '/devis',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesFacturesRoute =
  AuthenticatedVentesFacturesRouteImport.update({
    id: '/factures',
    path: '/factures',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesLivraisonsRoute =
  AuthenticatedVentesLivraisonsRouteImport.update({
    id: '/livraisons',
    path: '/livraisons',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesReglementsRoute =
  AuthenticatedVentesReglementsRouteImport.update({
    id: '/reglements',
    path: '/reglements',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)
const AuthenticatedVentesRetoursRoute =
  AuthenticatedVentesRetoursRouteImport.update({
    id: '/retours',
    path: '/retours',
    getParentRoute: () => AuthenticatedVentesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achats': typeof AuthenticatedAchatsRouteWithChildren
  '/alertes': typeof AuthenticatedAlertesRoute
  '/caisses': typeof AuthenticatedCaissesRouteWithChildren
  '/comptabilite': typeof AuthenticatedComptabiliteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donnees': typeof AuthenticatedDonneesRouteWithChildren
  '/materiel': typeof AuthenticatedMaterielRouteWithChildren
  '/personnel': typeof AuthenticatedPersonnelRouteWithChildren
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/stocks': typeof AuthenticatedStocksRouteWithChildren
  '/transport': typeof AuthenticatedTransportRouteWithChildren
  '/ventes': typeof AuthenticatedVentesRouteWithChildren
  '/achats/analyse': typeof AuthenticatedAchatsAnalyseRoute
  '/achats/avoirs': typeof AuthenticatedAchatsAvoirsRoute
  '/achats/demandes': typeof AuthenticatedAchatsDemandesRoute
  '/achats/factures': typeof AuthenticatedAchatsFacturesRoute
  '/achats/receptions': typeof AuthenticatedAchatsReceptionsRoute
  '/achats/reglements': typeof AuthenticatedAchatsReglementsRoute
  '/achats/retours': typeof AuthenticatedAchatsRetoursRoute
  '/caisses/alimentations': typeof AuthenticatedCaissesAlimentationsRoute
  '/caisses/analyse': typeof AuthenticatedCaissesAnalyseRoute
  '/caisses/depenses': typeof AuthenticatedCaissesDepensesRoute
  '/comptabilite/balance': typeof AuthenticatedComptabiliteBalanceRoute
  '/comptabilite/ecritures': typeof AuthenticatedComptabiliteEcrituresRoute
  '/comptabilite/etats': typeof AuthenticatedComptabiliteEtatsRoute
  '/comptabilite/grand-livre': typeof AuthenticatedComptabiliteGrandLivreRoute
  '/comptabilite/journaux': typeof AuthenticatedComptabiliteJournauxRoute
  '/comptabilite/plan': typeof AuthenticatedComptabilitePlanRoute
  '/comptabilite/rapprochement': typeof AuthenticatedComptabiliteRapprochementRoute
  '/donnees/clients': typeof AuthenticatedDonneesClientsRoute
  '/donnees/constituants': typeof AuthenticatedDonneesConstituantsRoute
  '/donnees/depots': typeof AuthenticatedDonneesDepotsRoute
  '/donnees/fournisseurs': typeof AuthenticatedDonneesFournisseursRoute
  '/donnees/log': typeof AuthenticatedDonneesLogRoute
  '/donnees/parametres': typeof AuthenticatedDonneesParametresRoute
  '/donnees/produits': typeof AuthenticatedDonneesProduitsRoute
  '/donnees/societe': typeof AuthenticatedDonneesSocieteRoute
  '/donnees/utilisateurs': typeof AuthenticatedDonneesUtilisateursRoute
  '/materiel/analyse': typeof AuthenticatedMaterielAnalyseRoute
  '/materiel/documents': typeof AuthenticatedMaterielDocumentsRoute
  '/materiel/entretiens': typeof AuthenticatedMaterielEntretiensRoute
  '/materiel/gasoil': typeof AuthenticatedMaterielGasoilRoute
  '/materiel/locations': typeof AuthenticatedMaterielLocationsRoute
  '/materiel/pannes': typeof AuthenticatedMaterielPannesRoute
  '/materiel/papiers': typeof AuthenticatedMaterielPapiersRoute
  '/materiel/periodiques': typeof AuthenticatedMaterielPeriodiquesRoute
  '/materiel/transferts': typeof AuthenticatedMaterielTransfertsRoute
  '/personnel/absences': typeof AuthenticatedPersonnelAbsencesRoute
  '/personnel/analyse': typeof AuthenticatedPersonnelAnalyseRoute
  '/personnel/avances': typeof AuthenticatedPersonnelAvancesRoute
  '/personnel/conges': typeof AuthenticatedPersonnelCongesRoute
  '/personnel/paie': typeof AuthenticatedPersonnelPaieRoute
  '/personnel/pointage': typeof AuthenticatedPersonnelPointageRoute
  '/production/analyse': typeof AuthenticatedProductionAnalyseRoute
  '/production/consommation': typeof AuthenticatedProductionConsommationRoute
  '/production/phases': typeof AuthenticatedProductionPhasesRoute
  '/production/rendement': typeof AuthenticatedProductionRendementRoute
  '/production/soustraitance': typeof AuthenticatedProductionSoustraitanceRoute
  '/production/soustraitance-audit': typeof AuthenticatedProductionSoustraitanceAuditRoute
  '/production/taches': typeof AuthenticatedProductionTachesRoute
  '/stocks/analyse': typeof AuthenticatedStocksAnalyseRoute
  '/stocks/inventaire': typeof AuthenticatedStocksInventaireRoute
  '/stocks/transferts': typeof AuthenticatedStocksTransfertsRoute
  '/transport/analyse': typeof AuthenticatedTransportAnalyseRoute
  '/transport/suivi': typeof AuthenticatedTransportSuiviRoute
  '/ventes/analyse': typeof AuthenticatedVentesAnalyseRoute
  '/ventes/avoirs': typeof AuthenticatedVentesAvoirsRoute
  '/ventes/commandes': typeof AuthenticatedVentesCommandesRoute
  '/ventes/devis': typeof AuthenticatedVentesDevisRoute
  '/ventes/factures': typeof AuthenticatedVentesFacturesRoute
  '/ventes/livraisons': typeof AuthenticatedVentesLivraisonsRoute
  '/ventes/reglements': typeof AuthenticatedVentesReglementsRoute
  '/ventes/retours': typeof AuthenticatedVentesRetoursRoute
  '/achats/': typeof AuthenticatedAchatsIndexRoute
  '/caisses/': typeof AuthenticatedCaissesIndexRoute
  '/comptabilite/': typeof AuthenticatedComptabiliteIndexRoute
  '/donnees/': typeof AuthenticatedDonneesIndexRoute
  '/materiel/': typeof AuthenticatedMaterielIndexRoute
  '/personnel/': typeof AuthenticatedPersonnelIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/stocks/': typeof AuthenticatedStocksIndexRoute
  '/transport/': typeof AuthenticatedTransportIndexRoute
  '/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertes': typeof AuthenticatedAlertesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/achats/analyse': typeof AuthenticatedAchatsAnalyseRoute
  '/achats/avoirs': typeof AuthenticatedAchatsAvoirsRoute
  '/achats/demandes': typeof AuthenticatedAchatsDemandesRoute
  '/achats/factures': typeof AuthenticatedAchatsFacturesRoute
  '/achats/receptions': typeof AuthenticatedAchatsReceptionsRoute
  '/achats/reglements': typeof AuthenticatedAchatsReglementsRoute
  '/achats/retours': typeof AuthenticatedAchatsRetoursRoute
  '/caisses/alimentations': typeof AuthenticatedCaissesAlimentationsRoute
  '/caisses/analyse': typeof AuthenticatedCaissesAnalyseRoute
  '/caisses/depenses': typeof AuthenticatedCaissesDepensesRoute
  '/comptabilite/balance': typeof AuthenticatedComptabiliteBalanceRoute
  '/comptabilite/ecritures': typeof AuthenticatedComptabiliteEcrituresRoute
  '/comptabilite/etats': typeof AuthenticatedComptabiliteEtatsRoute
  '/comptabilite/grand-livre': typeof AuthenticatedComptabiliteGrandLivreRoute
  '/comptabilite/journaux': typeof AuthenticatedComptabiliteJournauxRoute
  '/comptabilite/plan': typeof AuthenticatedComptabilitePlanRoute
  '/comptabilite/rapprochement': typeof AuthenticatedComptabiliteRapprochementRoute
  '/donnees/clients': typeof AuthenticatedDonneesClientsRoute
  '/donnees/constituants': typeof AuthenticatedDonneesConstituantsRoute
  '/donnees/depots': typeof AuthenticatedDonneesDepotsRoute
  '/donnees/fournisseurs': typeof AuthenticatedDonneesFournisseursRoute
  '/donnees/log': typeof AuthenticatedDonneesLogRoute
  '/donnees/parametres': typeof AuthenticatedDonneesParametresRoute
  '/donnees/produits': typeof AuthenticatedDonneesProduitsRoute
  '/donnees/societe': typeof AuthenticatedDonneesSocieteRoute
  '/donnees/utilisateurs': typeof AuthenticatedDonneesUtilisateursRoute
  '/materiel/analyse': typeof AuthenticatedMaterielAnalyseRoute
  '/materiel/documents': typeof AuthenticatedMaterielDocumentsRoute
  '/materiel/entretiens': typeof AuthenticatedMaterielEntretiensRoute
  '/materiel/gasoil': typeof AuthenticatedMaterielGasoilRoute
  '/materiel/locations': typeof AuthenticatedMaterielLocationsRoute
  '/materiel/pannes': typeof AuthenticatedMaterielPannesRoute
  '/materiel/papiers': typeof AuthenticatedMaterielPapiersRoute
  '/materiel/periodiques': typeof AuthenticatedMaterielPeriodiquesRoute
  '/materiel/transferts': typeof AuthenticatedMaterielTransfertsRoute
  '/personnel/absences': typeof AuthenticatedPersonnelAbsencesRoute
  '/personnel/analyse': typeof AuthenticatedPersonnelAnalyseRoute
  '/personnel/avances': typeof AuthenticatedPersonnelAvancesRoute
  '/personnel/conges': typeof AuthenticatedPersonnelCongesRoute
  '/personnel/paie': typeof AuthenticatedPersonnelPaieRoute
  '/personnel/pointage': typeof AuthenticatedPersonnelPointageRoute
  '/production/analyse': typeof AuthenticatedProductionAnalyseRoute
  '/production/consommation': typeof AuthenticatedProductionConsommationRoute
  '/production/phases': typeof AuthenticatedProductionPhasesRoute
  '/production/rendement': typeof AuthenticatedProductionRendementRoute
  '/production/soustraitance': typeof AuthenticatedProductionSoustraitanceRoute
  '/production/soustraitance-audit': typeof AuthenticatedProductionSoustraitanceAuditRoute
  '/production/taches': typeof AuthenticatedProductionTachesRoute
  '/stocks/analyse': typeof AuthenticatedStocksAnalyseRoute
  '/stocks/inventaire': typeof AuthenticatedStocksInventaireRoute
  '/stocks/transferts': typeof AuthenticatedStocksTransfertsRoute
  '/transport/analyse': typeof AuthenticatedTransportAnalyseRoute
  '/transport/suivi': typeof AuthenticatedTransportSuiviRoute
  '/ventes/analyse': typeof AuthenticatedVentesAnalyseRoute
  '/ventes/avoirs': typeof AuthenticatedVentesAvoirsRoute
  '/ventes/commandes': typeof AuthenticatedVentesCommandesRoute
  '/ventes/devis': typeof AuthenticatedVentesDevisRoute
  '/ventes/factures': typeof AuthenticatedVentesFacturesRoute
  '/ventes/livraisons': typeof AuthenticatedVentesLivraisonsRoute
  '/ventes/reglements': typeof AuthenticatedVentesReglementsRoute
  '/ventes/retours': typeof AuthenticatedVentesRetoursRoute
  '/achats': typeof AuthenticatedAchatsIndexRoute
  '/caisses': typeof AuthenticatedCaissesIndexRoute
  '/comptabilite': typeof AuthenticatedComptabiliteIndexRoute
  '/donnees': typeof AuthenticatedDonneesIndexRoute
  '/materiel': typeof AuthenticatedMaterielIndexRoute
  '/personnel': typeof AuthenticatedPersonnelIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/stocks': typeof AuthenticatedStocksIndexRoute
  '/transport': typeof AuthenticatedTransportIndexRoute
  '/ventes': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achats': typeof AuthenticatedAchatsRouteWithChildren
  '/_authenticated/alertes': typeof AuthenticatedAlertesRoute
  '/_authenticated/caisses': typeof AuthenticatedCaissesRouteWithChildren
  '/_authenticated/comptabilite': typeof AuthenticatedComptabiliteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donnees': typeof AuthenticatedDonneesRouteWithChildren
  '/_authenticated/materiel': typeof AuthenticatedMaterielRouteWithChildren
  '/_authenticated/personnel': typeof AuthenticatedPersonnelRouteWithChildren
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/stocks': typeof AuthenticatedStocksRouteWithChildren
  '/_authenticated/transport': typeof AuthenticatedTransportRouteWithChildren
  '/_authenticated/ventes': typeof AuthenticatedVentesRouteWithChildren
  '/_authenticated/achats/analyse': typeof AuthenticatedAchatsAnalyseRoute
  '/_authenticated/achats/avoirs': typeof AuthenticatedAchatsAvoirsRoute
  '/_authenticated/achats/demandes': typeof AuthenticatedAchatsDemandesRoute
  '/_authenticated/achats/factures': typeof AuthenticatedAchatsFacturesRoute
  '/_authenticated/achats/receptions': typeof AuthenticatedAchatsReceptionsRoute
  '/_authenticated/achats/reglements': typeof AuthenticatedAchatsReglementsRoute
  '/_authenticated/achats/retours': typeof AuthenticatedAchatsRetoursRoute
  '/_authenticated/caisses/alimentations': typeof AuthenticatedCaissesAlimentationsRoute
  '/_authenticated/caisses/analyse': typeof AuthenticatedCaissesAnalyseRoute
  '/_authenticated/caisses/depenses': typeof AuthenticatedCaissesDepensesRoute
  '/_authenticated/comptabilite/balance': typeof AuthenticatedComptabiliteBalanceRoute
  '/_authenticated/comptabilite/ecritures': typeof AuthenticatedComptabiliteEcrituresRoute
  '/_authenticated/comptabilite/etats': typeof AuthenticatedComptabiliteEtatsRoute
  '/_authenticated/comptabilite/grand-livre': typeof AuthenticatedComptabiliteGrandLivreRoute
  '/_authenticated/comptabilite/journaux': typeof AuthenticatedComptabiliteJournauxRoute
  '/_authenticated/comptabilite/plan': typeof AuthenticatedComptabilitePlanRoute
  '/_authenticated/comptabilite/rapprochement': typeof AuthenticatedComptabiliteRapprochementRoute
  '/_authenticated/donnees/clients': typeof AuthenticatedDonneesClientsRoute
  '/_authenticated/donnees/constituants': typeof AuthenticatedDonneesConstituantsRoute
  '/_authenticated/donnees/depots': typeof AuthenticatedDonneesDepotsRoute
  '/_authenticated/donnees/fournisseurs': typeof AuthenticatedDonneesFournisseursRoute
  '/_authenticated/donnees/log': typeof AuthenticatedDonneesLogRoute
  '/_authenticated/donnees/parametres': typeof AuthenticatedDonneesParametresRoute
  '/_authenticated/donnees/produits': typeof AuthenticatedDonneesProduitsRoute
  '/_authenticated/donnees/societe': typeof AuthenticatedDonneesSocieteRoute
  '/_authenticated/donnees/utilisateurs': typeof AuthenticatedDonneesUtilisateursRoute
  '/_authenticated/materiel/analyse': typeof AuthenticatedMaterielAnalyseRoute
  '/_authenticated/materiel/documents': typeof AuthenticatedMaterielDocumentsRoute
  '/_authenticated/materiel/entretiens': typeof AuthenticatedMaterielEntretiensRoute
  '/_authenticated/materiel/gasoil': typeof AuthenticatedMaterielGasoilRoute
  '/_authenticated/materiel/locations': typeof AuthenticatedMaterielLocationsRoute
  '/_authenticated/materiel/pannes': typeof AuthenticatedMaterielPannesRoute
  '/_authenticated/materiel/papiers': typeof AuthenticatedMaterielPapiersRoute
  '/_authenticated/materiel/periodiques': typeof AuthenticatedMaterielPeriodiquesRoute
  '/_authenticated/materiel/transferts': typeof AuthenticatedMaterielTransfertsRoute
  '/_authenticated/personnel/absences': typeof AuthenticatedPersonnelAbsencesRoute
  '/_authenticated/personnel/analyse': typeof AuthenticatedPersonnelAnalyseRoute
  '/_authenticated/personnel/avances': typeof AuthenticatedPersonnelAvancesRoute
  '/_authenticated/personnel/conges': typeof AuthenticatedPersonnelCongesRoute
  '/_authenticated/personnel/paie': typeof AuthenticatedPersonnelPaieRoute
  '/_authenticated/personnel/pointage': typeof AuthenticatedPersonnelPointageRoute
  '/_authenticated/production/analyse': typeof AuthenticatedProductionAnalyseRoute
  '/_authenticated/production/consommation': typeof AuthenticatedProductionConsommationRoute
  '/_authenticated/production/phases': typeof AuthenticatedProductionPhasesRoute
  '/_authenticated/production/rendement': typeof AuthenticatedProductionRendementRoute
  '/_authenticated/production/soustraitance': typeof AuthenticatedProductionSoustraitanceRoute
  '/_authenticated/production/soustraitance-audit': typeof AuthenticatedProductionSoustraitanceAuditRoute
  '/_authenticated/production/taches': typeof AuthenticatedProductionTachesRoute
  '/_authenticated/stocks/analyse': typeof AuthenticatedStocksAnalyseRoute
  '/_authenticated/stocks/inventaire': typeof AuthenticatedStocksInventaireRoute
  '/_authenticated/stocks/transferts': typeof AuthenticatedStocksTransfertsRoute
  '/_authenticated/transport/analyse': typeof AuthenticatedTransportAnalyseRoute
  '/_authenticated/transport/suivi': typeof AuthenticatedTransportSuiviRoute
  '/_authenticated/ventes/analyse': typeof AuthenticatedVentesAnalyseRoute
  '/_authenticated/ventes/avoirs': typeof AuthenticatedVentesAvoirsRoute
  '/_authenticated/ventes/commandes': typeof AuthenticatedVentesCommandesRoute
  '/_authenticated/ventes/devis': typeof AuthenticatedVentesDevisRoute
  '/_authenticated/ventes/factures': typeof AuthenticatedVentesFacturesRoute
  '/_authenticated/ventes/livraisons': typeof AuthenticatedVentesLivraisonsRoute
  '/_authenticated/ventes/reglements': typeof AuthenticatedVentesReglementsRoute
  '/_authenticated/ventes/retours': typeof AuthenticatedVentesRetoursRoute
  '/_authenticated/achats/': typeof AuthenticatedAchatsIndexRoute
  '/_authenticated/caisses/': typeof AuthenticatedCaissesIndexRoute
  '/_authenticated/comptabilite/': typeof AuthenticatedComptabiliteIndexRoute
  '/_authenticated/donnees/': typeof AuthenticatedDonneesIndexRoute
  '/_authenticated/materiel/': typeof AuthenticatedMaterielIndexRoute
  '/_authenticated/personnel/': typeof AuthenticatedPersonnelIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/stocks/': typeof AuthenticatedStocksIndexRoute
  '/_authenticated/transport/': typeof AuthenticatedTransportIndexRoute
  '/_authenticated/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achats'
    | '/alertes'
    | '/caisses'
    | '/comptabilite'
    | '/dashboard'
    | '/donnees'
    | '/materiel'
    | '/personnel'
    | '/production'
    | '/stocks'
    | '/transport'
    | '/ventes'
    | '/achats/analyse'
    | '/achats/avoirs'
    | '/achats/demandes'
    | '/achats/factures'
    | '/achats/receptions'
    | '/achats/reglements'
    | '/achats/retours'
    | '/caisses/alimentations'
    | '/caisses/analyse'
    | '/caisses/depenses'
    | '/comptabilite/balance'
    | '/comptabilite/ecritures'
    | '/comptabilite/etats'
    | '/comptabilite/grand-livre'
    | '/comptabilite/journaux'
    | '/comptabilite/plan'
    | '/comptabilite/rapprochement'
    | '/donnees/clients'
    | '/donnees/constituants'
    | '/donnees/depots'
    | '/donnees/fournisseurs'
    | '/donnees/log'
    | '/donnees/parametres'
    | '/donnees/produits'
    | '/donnees/societe'
    | '/donnees/utilisateurs'
    | '/materiel/analyse'
    | '/materiel/documents'
    | '/materiel/entretiens'
    | '/materiel/gasoil'
    | '/materiel/locations'
    | '/materiel/pannes'
    | '/materiel/papiers'
    | '/materiel/periodiques'
    | '/materiel/transferts'
    | '/personnel/absences'
    | '/personnel/analyse'
    | '/personnel/avances'
    | '/personnel/conges'
    | '/personnel/paie'
    | '/personnel/pointage'
    | '/production/analyse'
    | '/production/consommation'
    | '/production/phases'
    | '/production/rendement'
    | '/production/soustraitance'
    | '/production/soustraitance-audit'
    | '/production/taches'
    | '/stocks/analyse'
    | '/stocks/inventaire'
    | '/stocks/transferts'
    | '/transport/analyse'
    | '/transport/suivi'
    | '/ventes/analyse'
    | '/ventes/avoirs'
    | '/ventes/commandes'
    | '/ventes/devis'
    | '/ventes/factures'
    | '/ventes/livraisons'
    | '/ventes/reglements'
    | '/ventes/retours'
    | '/achats/'
    | '/caisses/'
    | '/comptabilite/'
    | '/donnees/'
    | '/materiel/'
    | '/personnel/'
    | '/production/'
    | '/stocks/'
    | '/transport/'
    | '/ventes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alertes'
    | '/dashboard'
    | '/achats/analyse'
    | '/achats/avoirs'
    | '/achats/demandes'
    | '/achats/factures'
    | '/achats/receptions'
    | '/achats/reglements'
    | '/achats/retours'
    | '/caisses/alimentations'
    | '/caisses/analyse'
    | '/caisses/depenses'
    | '/comptabilite/balance'
    | '/comptabilite/ecritures'
    | '/comptabilite/etats'
    | '/comptabilite/grand-livre'
    | '/comptabilite/journaux'
    | '/comptabilite/plan'
    | '/comptabilite/rapprochement'
    | '/donnees/clients'
    | '/donnees/constituants'
    | '/donnees/depots'
    | '/donnees/fournisseurs'
    | '/donnees/log'
    | '/donnees/parametres'
    | '/donnees/produits'
    | '/donnees/societe'
    | '/donnees/utilisateurs'
    | '/materiel/analyse'
    | '/materiel/documents'
    | '/materiel/entretiens'
    | '/materiel/gasoil'
    | '/materiel/locations'
    | '/materiel/pannes'
    | '/materiel/papiers'
    | '/materiel/periodiques'
    | '/materiel/transferts'
    | '/personnel/absences'
    | '/personnel/analyse'
    | '/personnel/avances'
    | '/personnel/conges'
    | '/personnel/paie'
    | '/personnel/pointage'
    | '/production/analyse'
    | '/production/consommation'
    | '/production/phases'
    | '/production/rendement'
    | '/production/soustraitance'
    | '/production/soustraitance-audit'
    | '/production/taches'
    | '/stocks/analyse'
    | '/stocks/inventaire'
    | '/stocks/transferts'
    | '/transport/analyse'
    | '/transport/suivi'
    | '/ventes/analyse'
    | '/ventes/avoirs'
    | '/ventes/commandes'
    | '/ventes/devis'
    | '/ventes/factures'
    | '/ventes/livraisons'
    | '/ventes/reglements'
    | '/ventes/retours'
    | '/achats'
    | '/caisses'
    | '/comptabilite'
    | '/donnees'
    | '/materiel'
    | '/personnel'
    | '/production'
    | '/stocks'
    | '/transport'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achats'
    | '/_authenticated/alertes'
    | '/_authenticated/caisses'
    | '/_authenticated/comptabilite'
    | '/_authenticated/dashboard'
    | '/_authenticated/donnees'
    | '/_authenticated/materiel'
    | '/_authenticated/personnel'
    | '/_authenticated/production'
    | '/_authenticated/stocks'
    | '/_authenticated/transport'
    | '/_authenticated/ventes'
    | '/_authenticated/achats/analyse'
    | '/_authenticated/achats/avoirs'
    | '/_authenticated/achats/demandes'
    | '/_authenticated/achats/factures'
    | '/_authenticated/achats/receptions'
    | '/_authenticated/achats/reglements'
    | '/_authenticated/achats/retours'
    | '/_authenticated/caisses/alimentations'
    | '/_authenticated/caisses/analyse'
    | '/_authenticated/caisses/depenses'
    | '/_authenticated/comptabilite/balance'
    | '/_authenticated/comptabilite/ecritures'
    | '/_authenticated/comptabilite/etats'
    | '/_authenticated/comptabilite/grand-livre'
    | '/_authenticated/comptabilite/journaux'
    | '/_authenticated/comptabilite/plan'
    | '/_authenticated/comptabilite/rapprochement'
    | '/_authenticated/donnees/clients'
    | '/_authenticated/donnees/constituants'
    | '/_authenticated/donnees/depots'
    | '/_authenticated/donnees/fournisseurs'
    | '/_authenticated/donnees/log'
    | '/_authenticated/donnees/parametres'
    | '/_authenticated/donnees/produits'
    | '/_authenticated/donnees/societe'
    | '/_authenticated/donnees/utilisateurs'
    | '/_authenticated/materiel/analyse'
    | '/_authenticated/materiel/documents'
    | '/_authenticated/materiel/entretiens'
    | '/_authenticated/materiel/gasoil'
    | '/_authenticated/materiel/locations'
    | '/_authenticated/materiel/pannes'
    | '/_authenticated/materiel/papiers'
    | '/_authenticated/materiel/periodiques'
    | '/_authenticated/materiel/transferts'
    | '/_authenticated/personnel/absences'
    | '/_authenticated/personnel/analyse'
    | '/_authenticated/personnel/avances'
    | '/_authenticated/personnel/conges'
    | '/_authenticated/personnel/paie'
    | '/_authenticated/personnel/pointage'
    | '/_authenticated/production/analyse'
    | '/_authenticated/production/consommation'
    | '/_authenticated/production/phases'
    | '/_authenticated/production/rendement'
    | '/_authenticated/production/soustraitance'
    | '/_authenticated/production/soustraitance-audit'
    | '/_authenticated/production/taches'
    | '/_authenticated/stocks/analyse'
    | '/_authenticated/stocks/inventaire'
    | '/_authenticated/stocks/transferts'
    | '/_authenticated/transport/analyse'
    | '/_authenticated/transport/suivi'
    | '/_authenticated/ventes/analyse'
    | '/_authenticated/ventes/avoirs'
    | '/_authenticated/ventes/commandes'
    | '/_authenticated/ventes/devis'
    | '/_authenticated/ventes/factures'
    | '/_authenticated/ventes/livraisons'
    | '/_authenticated/ventes/reglements'
    | '/_authenticated/ventes/retours'
    | '/_authenticated/achats/'
    | '/_authenticated/caisses/'
    | '/_authenticated/comptabilite/'
    | '/_authenticated/donnees/'
    | '/_authenticated/materiel/'
    | '/_authenticated/personnel/'
    | '/_authenticated/production/'
    | '/_authenticated/stocks/'
    | '/_authenticated/transport/'
    | '/_authenticated/ventes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achats': {
      id: '/_authenticated/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AuthenticatedAchatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertes': {
      id: '/_authenticated/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AuthenticatedAlertesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caisses': {
      id: '/_authenticated/caisses'
      path: '/caisses'
      fullPath: '/caisses'
      preLoaderRoute: typeof AuthenticatedCaissesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comptabilite': {
      id: '/_authenticated/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AuthenticatedComptabiliteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donnees': {
      id: '/_authenticated/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof AuthenticatedDonneesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiel': {
      id: '/_authenticated/materiel'
      path: '/materiel'
      fullPath: '/materiel'
      preLoaderRoute: typeof AuthenticatedMaterielRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnel': {
      id: '/_authenticated/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achats/': {
      id: '/_authenticated/achats/'
      path: '/'
      fullPath: '/achats/'
      preLoaderRoute: typeof AuthenticatedAchatsIndexRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/analyse': {
      id: '/_authenticated/achats/analyse'
      path: '/analyse'
      fullPath: '/achats/analyse'
      preLoaderRoute: typeof AuthenticatedAchatsAnalyseRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/avoirs': {
      id: '/_authenticated/achats/avoirs'
      path: '/avoirs'
      fullPath: '/achats/avoirs'
      preLoaderRoute: typeof AuthenticatedAchatsAvoirsRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/demandes': {
      id: '/_authenticated/achats/demandes'
      path: '/demandes'
      fullPath: '/achats/demandes'
      preLoaderRoute: typeof AuthenticatedAchatsDemandesRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/factures': {
      id: '/_authenticated/achats/factures'
      path: '/factures'
      fullPath: '/achats/factures'
      preLoaderRoute: typeof AuthenticatedAchatsFacturesRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/receptions': {
      id: '/_authenticated/achats/receptions'
      path: '/receptions'
      fullPath: '/achats/receptions'
      preLoaderRoute: typeof AuthenticatedAchatsReceptionsRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/reglements': {
      id: '/_authenticated/achats/reglements'
      path: '/reglements'
      fullPath: '/achats/reglements'
      preLoaderRoute: typeof AuthenticatedAchatsReglementsRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/achats/retours': {
      id: '/_authenticated/achats/retours'
      path: '/retours'
      fullPath: '/achats/retours'
      preLoaderRoute: typeof AuthenticatedAchatsRetoursRouteImport
      parentRoute: typeof AuthenticatedAchatsRoute
    }
    '/_authenticated/caisses/': {
      id: '/_authenticated/caisses/'
      path: '/'
      fullPath: '/caisses/'
      preLoaderRoute: typeof AuthenticatedCaissesIndexRouteImport
      parentRoute: typeof AuthenticatedCaissesRoute
    }
    '/_authenticated/caisses/alimentations': {
      id: '/_authenticated/caisses/alimentations'
      path: '/alimentations'
      fullPath: '/caisses/alimentations'
      preLoaderRoute: typeof AuthenticatedCaissesAlimentationsRouteImport
      parentRoute: typeof AuthenticatedCaissesRoute
    }
    '/_authenticated/caisses/analyse': {
      id: '/_authenticated/caisses/analyse'
      path: '/analyse'
      fullPath: '/caisses/analyse'
      preLoaderRoute: typeof AuthenticatedCaissesAnalyseRouteImport
      parentRoute: typeof AuthenticatedCaissesRoute
    }
    '/_authenticated/caisses/depenses': {
      id: '/_authenticated/caisses/depenses'
      path: '/depenses'
      fullPath: '/caisses/depenses'
      preLoaderRoute: typeof AuthenticatedCaissesDepensesRouteImport
      parentRoute: typeof AuthenticatedCaissesRoute
    }
    '/_authenticated/comptabilite/': {
      id: '/_authenticated/comptabilite/'
      path: '/'
      fullPath: '/comptabilite/'
      preLoaderRoute: typeof AuthenticatedComptabiliteIndexRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/balance': {
      id: '/_authenticated/comptabilite/balance'
      path: '/balance'
      fullPath: '/comptabilite/balance'
      preLoaderRoute: typeof AuthenticatedComptabiliteBalanceRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/ecritures': {
      id: '/_authenticated/comptabilite/ecritures'
      path: '/ecritures'
      fullPath: '/comptabilite/ecritures'
      preLoaderRoute: typeof AuthenticatedComptabiliteEcrituresRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/etats': {
      id: '/_authenticated/comptabilite/etats'
      path: '/etats'
      fullPath: '/comptabilite/etats'
      preLoaderRoute: typeof AuthenticatedComptabiliteEtatsRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/grand-livre': {
      id: '/_authenticated/comptabilite/grand-livre'
      path: '/grand-livre'
      fullPath: '/comptabilite/grand-livre'
      preLoaderRoute: typeof AuthenticatedComptabiliteGrandLivreRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/journaux': {
      id: '/_authenticated/comptabilite/journaux'
      path: '/journaux'
      fullPath: '/comptabilite/journaux'
      preLoaderRoute: typeof AuthenticatedComptabiliteJournauxRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/plan': {
      id: '/_authenticated/comptabilite/plan'
      path: '/plan'
      fullPath: '/comptabilite/plan'
      preLoaderRoute: typeof AuthenticatedComptabilitePlanRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/rapprochement': {
      id: '/_authenticated/comptabilite/rapprochement'
      path: '/rapprochement'
      fullPath: '/comptabilite/rapprochement'
      preLoaderRoute: typeof AuthenticatedComptabiliteRapprochementRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/donnees/': {
      id: '/_authenticated/donnees/'
      path: '/'
      fullPath: '/donnees/'
      preLoaderRoute: typeof AuthenticatedDonneesIndexRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/clients': {
      id: '/_authenticated/donnees/clients'
      path: '/clients'
      fullPath: '/donnees/clients'
      preLoaderRoute: typeof AuthenticatedDonneesClientsRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/constituants': {
      id: '/_authenticated/donnees/constituants'
      path: '/constituants'
      fullPath: '/donnees/constituants'
      preLoaderRoute: typeof AuthenticatedDonneesConstituantsRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/depots': {
      id: '/_authenticated/donnees/depots'
      path: '/depots'
      fullPath: '/donnees/depots'
      preLoaderRoute: typeof AuthenticatedDonneesDepotsRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/fournisseurs': {
      id: '/_authenticated/donnees/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/donnees/fournisseurs'
      preLoaderRoute: typeof AuthenticatedDonneesFournisseursRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/log': {
      id: '/_authenticated/donnees/log'
      path: '/log'
      fullPath: '/donnees/log'
      preLoaderRoute: typeof AuthenticatedDonneesLogRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/parametres': {
      id: '/_authenticated/donnees/parametres'
      path: '/parametres'
      fullPath: '/donnees/parametres'
      preLoaderRoute: typeof AuthenticatedDonneesParametresRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/produits': {
      id: '/_authenticated/donnees/produits'
      path: '/produits'
      fullPath: '/donnees/produits'
      preLoaderRoute: typeof AuthenticatedDonneesProduitsRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/societe': {
      id: '/_authenticated/donnees/societe'
      path: '/societe'
      fullPath: '/donnees/societe'
      preLoaderRoute: typeof AuthenticatedDonneesSocieteRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/donnees/utilisateurs': {
      id: '/_authenticated/donnees/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/donnees/utilisateurs'
      preLoaderRoute: typeof AuthenticatedDonneesUtilisateursRouteImport
      parentRoute: typeof AuthenticatedDonneesRoute
    }
    '/_authenticated/materiel/': {
      id: '/_authenticated/materiel/'
      path: '/'
      fullPath: '/materiel/'
      preLoaderRoute: typeof AuthenticatedMaterielIndexRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/analyse': {
      id: '/_authenticated/materiel/analyse'
      path: '/analyse'
      fullPath: '/materiel/analyse'
      preLoaderRoute: typeof AuthenticatedMaterielAnalyseRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/documents': {
      id: '/_authenticated/materiel/documents'
      path: '/documents'
      fullPath: '/materiel/documents'
      preLoaderRoute: typeof AuthenticatedMaterielDocumentsRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/entretiens': {
      id: '/_authenticated/materiel/entretiens'
      path: '/entretiens'
      fullPath: '/materiel/entretiens'
      preLoaderRoute: typeof AuthenticatedMaterielEntretiensRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/gasoil': {
      id: '/_authenticated/materiel/gasoil'
      path: '/gasoil'
      fullPath: '/materiel/gasoil'
      preLoaderRoute: typeof AuthenticatedMaterielGasoilRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/locations': {
      id: '/_authenticated/materiel/locations'
      path: '/locations'
      fullPath: '/materiel/locations'
      preLoaderRoute: typeof AuthenticatedMaterielLocationsRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/pannes': {
      id: '/_authenticated/materiel/pannes'
      path: '/pannes'
      fullPath: '/materiel/pannes'
      preLoaderRoute: typeof AuthenticatedMaterielPannesRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/papiers': {
      id: '/_authenticated/materiel/papiers'
      path: '/papiers'
      fullPath: '/materiel/papiers'
      preLoaderRoute: typeof AuthenticatedMaterielPapiersRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/periodiques': {
      id: '/_authenticated/materiel/periodiques'
      path: '/periodiques'
      fullPath: '/materiel/periodiques'
      preLoaderRoute: typeof AuthenticatedMaterielPeriodiquesRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/materiel/transferts': {
      id: '/_authenticated/materiel/transferts'
      path: '/transferts'
      fullPath: '/materiel/transferts'
      preLoaderRoute: typeof AuthenticatedMaterielTransfertsRouteImport
      parentRoute: typeof AuthenticatedMaterielRoute
    }
    '/_authenticated/personnel/': {
      id: '/_authenticated/personnel/'
      path: '/'
      fullPath: '/personnel/'
      preLoaderRoute: typeof AuthenticatedPersonnelIndexRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/absences': {
      id: '/_authenticated/personnel/absences'
      path: '/absences'
      fullPath: '/personnel/absences'
      preLoaderRoute: typeof AuthenticatedPersonnelAbsencesRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/analyse': {
      id: '/_authenticated/personnel/analyse'
      path: '/analyse'
      fullPath: '/personnel/analyse'
      preLoaderRoute: typeof AuthenticatedPersonnelAnalyseRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/avances': {
      id: '/_authenticated/personnel/avances'
      path: '/avances'
      fullPath: '/personnel/avances'
      preLoaderRoute: typeof AuthenticatedPersonnelAvancesRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/conges': {
      id: '/_authenticated/personnel/conges'
      path: '/conges'
      fullPath: '/personnel/conges'
      preLoaderRoute: typeof AuthenticatedPersonnelCongesRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/paie': {
      id: '/_authenticated/personnel/paie'
      path: '/paie'
      fullPath: '/personnel/paie'
      preLoaderRoute: typeof AuthenticatedPersonnelPaieRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/pointage': {
      id: '/_authenticated/personnel/pointage'
      path: '/pointage'
      fullPath: '/personnel/pointage'
      preLoaderRoute: typeof AuthenticatedPersonnelPointageRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/analyse': {
      id: '/_authenticated/production/analyse'
      path: '/analyse'
      fullPath: '/production/analyse'
      preLoaderRoute: typeof AuthenticatedProductionAnalyseRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/consommation': {
      id: '/_authenticated/production/consommation'
      path: '/consommation'
      fullPath: '/production/consommation'
      preLoaderRoute: typeof AuthenticatedProductionConsommationRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/phases': {
      id: '/_authenticated/production/phases'
      path: '/phases'
      fullPath: '/production/phases'
      preLoaderRoute: typeof AuthenticatedProductionPhasesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/rendement': {
      id: '/_authenticated/production/rendement'
      path: '/rendement'
      fullPath: '/production/rendement'
      preLoaderRoute: typeof AuthenticatedProductionRendementRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/soustraitance': {
      id: '/_authenticated/production/soustraitance'
      path: '/soustraitance'
      fullPath: '/production/soustraitance'
      preLoaderRoute: typeof AuthenticatedProductionSoustraitanceRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/soustraitance-audit': {
      id: '/_authenticated/production/soustraitance-audit'
      path: '/soustraitance-audit'
      fullPath: '/production/soustraitance-audit'
      preLoaderRoute: typeof AuthenticatedProductionSoustraitanceAuditRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/taches': {
      id: '/_authenticated/production/taches'
      path: '/taches'
      fullPath: '/production/taches'
      preLoaderRoute: typeof AuthenticatedProductionTachesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/stocks/': {
      id: '/_authenticated/stocks/'
      path: '/'
      fullPath: '/stocks/'
      preLoaderRoute: typeof AuthenticatedStocksIndexRouteImport
      parentRoute: typeof AuthenticatedStocksRoute
    }
    '/_authenticated/stocks/analyse': {
      id: '/_authenticated/stocks/analyse'
      path: '/analyse'
      fullPath: '/stocks/analyse'
      preLoaderRoute: typeof AuthenticatedStocksAnalyseRouteImport
      parentRoute: typeof AuthenticatedStocksRoute
    }
    '/_authenticated/stocks/inventaire': {
      id: '/_authenticated/stocks/inventaire'
      path: '/inventaire'
      fullPath: '/stocks/inventaire'
      preLoaderRoute: typeof AuthenticatedStocksInventaireRouteImport
      parentRoute: typeof AuthenticatedStocksRoute
    }
    '/_authenticated/stocks/transferts': {
      id: '/_authenticated/stocks/transferts'
      path: '/transferts'
      fullPath: '/stocks/transferts'
      preLoaderRoute: typeof AuthenticatedStocksTransfertsRouteImport
      parentRoute: typeof AuthenticatedStocksRoute
    }
    '/_authenticated/transport/': {
      id: '/_authenticated/transport/'
      path: '/'
      fullPath: '/transport/'
      preLoaderRoute: typeof AuthenticatedTransportIndexRouteImport
      parentRoute: typeof AuthenticatedTransportRoute
    }
    '/_authenticated/transport/analyse': {
      id: '/_authenticated/transport/analyse'
      path: '/analyse'
      fullPath: '/transport/analyse'
      preLoaderRoute: typeof AuthenticatedTransportAnalyseRouteImport
      parentRoute: typeof AuthenticatedTransportRoute
    }
    '/_authenticated/transport/suivi': {
      id: '/_authenticated/transport/suivi'
      path: '/suivi'
      fullPath: '/transport/suivi'
      preLoaderRoute: typeof AuthenticatedTransportSuiviRouteImport
      parentRoute: typeof AuthenticatedTransportRoute
    }
    '/_authenticated/ventes/': {
      id: '/_authenticated/ventes/'
      path: '/'
      fullPath: '/ventes/'
      preLoaderRoute: typeof AuthenticatedVentesIndexRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/analyse': {
      id: '/_authenticated/ventes/analyse'
      path: '/analyse'
      fullPath: '/ventes/analyse'
      preLoaderRoute: typeof AuthenticatedVentesAnalyseRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/avoirs': {
      id: '/_authenticated/ventes/avoirs'
      path: '/avoirs'
      fullPath: '/ventes/avoirs'
      preLoaderRoute: typeof AuthenticatedVentesAvoirsRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/commandes': {
      id: '/_authenticated/ventes/commandes'
      path: '/commandes'
      fullPath: '/ventes/commandes'
      preLoaderRoute: typeof AuthenticatedVentesCommandesRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/devis': {
      id: '/_authenticated/ventes/devis'
      path: '/devis'
      fullPath: '/ventes/devis'
      preLoaderRoute: typeof AuthenticatedVentesDevisRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/factures': {
      id: '/_authenticated/ventes/factures'
      path: '/factures'
      fullPath: '/ventes/factures'
      preLoaderRoute: typeof AuthenticatedVentesFacturesRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/livraisons': {
      id: '/_authenticated/ventes/livraisons'
      path: '/livraisons'
      fullPath: '/ventes/livraisons'
      preLoaderRoute: typeof AuthenticatedVentesLivraisonsRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/reglements': {
      id: '/_authenticated/ventes/reglements'
      path: '/reglements'
      fullPath: '/ventes/reglements'
      preLoaderRoute: typeof AuthenticatedVentesReglementsRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
    '/_authenticated/ventes/retours': {
      id: '/_authenticated/ventes/retours'
      path: '/retours'
      fullPath: '/ventes/retours'
      preLoaderRoute: typeof AuthenticatedVentesRetoursRouteImport
      parentRoute: typeof AuthenticatedVentesRoute
    }
  }
}

interface AuthenticatedAchatsRouteChildren {
  AuthenticatedAchatsAnalyseRoute: typeof AuthenticatedAchatsAnalyseRoute
  AuthenticatedAchatsAvoirsRoute: typeof AuthenticatedAchatsAvoirsRoute
  AuthenticatedAchatsDemandesRoute: typeof AuthenticatedAchatsDemandesRoute
  AuthenticatedAchatsFacturesRoute: typeof AuthenticatedAchatsFacturesRoute
  AuthenticatedAchatsReceptionsRoute: typeof AuthenticatedAchatsReceptionsRoute
  AuthenticatedAchatsReglementsRoute: typeof AuthenticatedAchatsReglementsRoute
  AuthenticatedAchatsRetoursRoute: typeof AuthenticatedAchatsRetoursRoute
  AuthenticatedAchatsIndexRoute: typeof AuthenticatedAchatsIndexRoute
}

const AuthenticatedAchatsRouteChildren: AuthenticatedAchatsRouteChildren = {
  AuthenticatedAchatsAnalyseRoute: AuthenticatedAchatsAnalyseRoute,
  AuthenticatedAchatsAvoirsRoute: AuthenticatedAchatsAvoirsRoute,
  AuthenticatedAchatsDemandesRoute: AuthenticatedAchatsDemandesRoute,
  AuthenticatedAchatsFacturesRoute: AuthenticatedAchatsFacturesRoute,
  AuthenticatedAchatsReceptionsRoute: AuthenticatedAchatsReceptionsRoute,
  AuthenticatedAchatsReglementsRoute: AuthenticatedAchatsReglementsRoute,
  AuthenticatedAchatsRetoursRoute: AuthenticatedAchatsRetoursRoute,
  AuthenticatedAchatsIndexRoute: AuthenticatedAchatsIndexRoute,
}

const AuthenticatedAchatsRouteWithChildren =
  AuthenticatedAchatsRoute._addFileChildren(AuthenticatedAchatsRouteChildren)

interface AuthenticatedCaissesRouteChildren {
  AuthenticatedCaissesAlimentationsRoute: typeof AuthenticatedCaissesAlimentationsRoute
  AuthenticatedCaissesAnalyseRoute: typeof AuthenticatedCaissesAnalyseRoute
  AuthenticatedCaissesDepensesRoute: typeof AuthenticatedCaissesDepensesRoute
  AuthenticatedCaissesIndexRoute: typeof AuthenticatedCaissesIndexRoute
}

const AuthenticatedCaissesRouteChildren: AuthenticatedCaissesRouteChildren = {
  AuthenticatedCaissesAlimentationsRoute:
    AuthenticatedCaissesAlimentationsRoute,
  AuthenticatedCaissesAnalyseRoute: AuthenticatedCaissesAnalyseRoute,
  AuthenticatedCaissesDepensesRoute: AuthenticatedCaissesDepensesRoute,
  AuthenticatedCaissesIndexRoute: AuthenticatedCaissesIndexRoute,
}

const AuthenticatedCaissesRouteWithChildren =
  AuthenticatedCaissesRoute._addFileChildren(AuthenticatedCaissesRouteChildren)

interface AuthenticatedComptabiliteRouteChildren {
  AuthenticatedComptabiliteBalanceRoute: typeof AuthenticatedComptabiliteBalanceRoute
  AuthenticatedComptabiliteEcrituresRoute: typeof AuthenticatedComptabiliteEcrituresRoute
  AuthenticatedComptabiliteEtatsRoute: typeof AuthenticatedComptabiliteEtatsRoute
  AuthenticatedComptabiliteGrandLivreRoute: typeof AuthenticatedComptabiliteGrandLivreRoute
  AuthenticatedComptabiliteJournauxRoute: typeof AuthenticatedComptabiliteJournauxRoute
  AuthenticatedComptabilitePlanRoute: typeof AuthenticatedComptabilitePlanRoute
  AuthenticatedComptabiliteRapprochementRoute: typeof AuthenticatedComptabiliteRapprochementRoute
  AuthenticatedComptabiliteIndexRoute: typeof AuthenticatedComptabiliteIndexRoute
}

const AuthenticatedComptabiliteRouteChildren: AuthenticatedComptabiliteRouteChildren =
  {
    AuthenticatedComptabiliteBalanceRoute:
      AuthenticatedComptabiliteBalanceRoute,
    AuthenticatedComptabiliteEcrituresRoute:
      AuthenticatedComptabiliteEcrituresRoute,
    AuthenticatedComptabiliteEtatsRoute: AuthenticatedComptabiliteEtatsRoute,
    AuthenticatedComptabiliteGrandLivreRoute:
      AuthenticatedComptabiliteGrandLivreRoute,
    AuthenticatedComptabiliteJournauxRoute:
      AuthenticatedComptabiliteJournauxRoute,
    AuthenticatedComptabilitePlanRoute: AuthenticatedComptabilitePlanRoute,
    AuthenticatedComptabiliteRapprochementRoute:
      AuthenticatedComptabiliteRapprochementRoute,
    AuthenticatedComptabiliteIndexRoute: AuthenticatedComptabiliteIndexRoute,
  }

const AuthenticatedComptabiliteRouteWithChildren =
  AuthenticatedComptabiliteRoute._addFileChildren(
    AuthenticatedComptabiliteRouteChildren,
  )

interface AuthenticatedDonneesRouteChildren {
  AuthenticatedDonneesClientsRoute: typeof AuthenticatedDonneesClientsRoute
  AuthenticatedDonneesConstituantsRoute: typeof AuthenticatedDonneesConstituantsRoute
  AuthenticatedDonneesDepotsRoute: typeof AuthenticatedDonneesDepotsRoute
  AuthenticatedDonneesFournisseursRoute: typeof AuthenticatedDonneesFournisseursRoute
  AuthenticatedDonneesLogRoute: typeof AuthenticatedDonneesLogRoute
  AuthenticatedDonneesParametresRoute: typeof AuthenticatedDonneesParametresRoute
  AuthenticatedDonneesProduitsRoute: typeof AuthenticatedDonneesProduitsRoute
  AuthenticatedDonneesSocieteRoute: typeof AuthenticatedDonneesSocieteRoute
  AuthenticatedDonneesUtilisateursRoute: typeof AuthenticatedDonneesUtilisateursRoute
  AuthenticatedDonneesIndexRoute: typeof AuthenticatedDonneesIndexRoute
}

const AuthenticatedDonneesRouteChildren: AuthenticatedDonneesRouteChildren = {
  AuthenticatedDonneesClientsRoute: AuthenticatedDonneesClientsRoute,
  AuthenticatedDonneesConstituantsRoute: AuthenticatedDonneesConstituantsRoute,
  AuthenticatedDonneesDepotsRoute: AuthenticatedDonneesDepotsRoute,
  AuthenticatedDonneesFournisseursRoute: AuthenticatedDonneesFournisseursRoute,
  AuthenticatedDonneesLogRoute: AuthenticatedDonneesLogRoute,
  AuthenticatedDonneesParametresRoute: AuthenticatedDonneesParametresRoute,
  AuthenticatedDonneesProduitsRoute: AuthenticatedDonneesProduitsRoute,
  AuthenticatedDonneesSocieteRoute: AuthenticatedDonneesSocieteRoute,
  AuthenticatedDonneesUtilisateursRoute: AuthenticatedDonneesUtilisateursRoute,
  AuthenticatedDonneesIndexRoute: AuthenticatedDonneesIndexRoute,
}

const AuthenticatedDonneesRouteWithChildren =
  AuthenticatedDonneesRoute._addFileChildren(AuthenticatedDonneesRouteChildren)

interface AuthenticatedMaterielRouteChildren {
  AuthenticatedMaterielAnalyseRoute: typeof AuthenticatedMaterielAnalyseRoute
  AuthenticatedMaterielDocumentsRoute: typeof AuthenticatedMaterielDocumentsRoute
  AuthenticatedMaterielEntretiensRoute: typeof AuthenticatedMaterielEntretiensRoute
  AuthenticatedMaterielGasoilRoute: typeof AuthenticatedMaterielGasoilRoute
  AuthenticatedMaterielLocationsRoute: typeof AuthenticatedMaterielLocationsRoute
  AuthenticatedMaterielPannesRoute: typeof AuthenticatedMaterielPannesRoute
  AuthenticatedMaterielPapiersRoute: typeof AuthenticatedMaterielPapiersRoute
  AuthenticatedMaterielPeriodiquesRoute: typeof AuthenticatedMaterielPeriodiquesRoute
  AuthenticatedMaterielTransfertsRoute: typeof AuthenticatedMaterielTransfertsRoute
  AuthenticatedMaterielIndexRoute: typeof AuthenticatedMaterielIndexRoute
}

const AuthenticatedMaterielRouteChildren: AuthenticatedMaterielRouteChildren = {
  AuthenticatedMaterielAnalyseRoute: AuthenticatedMaterielAnalyseRoute,
  AuthenticatedMaterielDocumentsRoute: AuthenticatedMaterielDocumentsRoute,
  AuthenticatedMaterielEntretiensRoute: AuthenticatedMaterielEntretiensRoute,
  AuthenticatedMaterielGasoilRoute: AuthenticatedMaterielGasoilRoute,
  AuthenticatedMaterielLocationsRoute: AuthenticatedMaterielLocationsRoute,
  AuthenticatedMaterielPannesRoute: AuthenticatedMaterielPannesRoute,
  AuthenticatedMaterielPapiersRoute: AuthenticatedMaterielPapiersRoute,
  AuthenticatedMaterielPeriodiquesRoute: AuthenticatedMaterielPeriodiquesRoute,
  AuthenticatedMaterielTransfertsRoute: AuthenticatedMaterielTransfertsRoute,
  AuthenticatedMaterielIndexRoute: AuthenticatedMaterielIndexRoute,
}

const AuthenticatedMaterielRouteWithChildren =
  AuthenticatedMaterielRoute._addFileChildren(
    AuthenticatedMaterielRouteChildren,
  )

interface AuthenticatedPersonnelRouteChildren {
  AuthenticatedPersonnelAbsencesRoute: typeof AuthenticatedPersonnelAbsencesRoute
  AuthenticatedPersonnelAnalyseRoute: typeof AuthenticatedPersonnelAnalyseRoute
  AuthenticatedPersonnelAvancesRoute: typeof AuthenticatedPersonnelAvancesRoute
  AuthenticatedPersonnelCongesRoute: typeof AuthenticatedPersonnelCongesRoute
  AuthenticatedPersonnelPaieRoute: typeof AuthenticatedPersonnelPaieRoute
  AuthenticatedPersonnelPointageRoute: typeof AuthenticatedPersonnelPointageRoute
  AuthenticatedPersonnelIndexRoute: typeof AuthenticatedPersonnelIndexRoute
}

const AuthenticatedPersonnelRouteChildren: AuthenticatedPersonnelRouteChildren =
  {
    AuthenticatedPersonnelAbsencesRoute: AuthenticatedPersonnelAbsencesRoute,
    AuthenticatedPersonnelAnalyseRoute: AuthenticatedPersonnelAnalyseRoute,
    AuthenticatedPersonnelAvancesRoute: AuthenticatedPersonnelAvancesRoute,
    AuthenticatedPersonnelCongesRoute: AuthenticatedPersonnelCongesRoute,
    AuthenticatedPersonnelPaieRoute: AuthenticatedPersonnelPaieRoute,
    AuthenticatedPersonnelPointageRoute: AuthenticatedPersonnelPointageRoute,
    AuthenticatedPersonnelIndexRoute: AuthenticatedPersonnelIndexRoute,
  }

const AuthenticatedPersonnelRouteWithChildren =
  AuthenticatedPersonnelRoute._addFileChildren(
    AuthenticatedPersonnelRouteChildren,
  )

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionAnalyseRoute: typeof AuthenticatedProductionAnalyseRoute
  AuthenticatedProductionConsommationRoute: typeof AuthenticatedProductionConsommationRoute
  AuthenticatedProductionPhasesRoute: typeof AuthenticatedProductionPhasesRoute
  AuthenticatedProductionRendementRoute: typeof AuthenticatedProductionRendementRoute
  AuthenticatedProductionSoustraitanceRoute: typeof AuthenticatedProductionSoustraitanceRoute
  AuthenticatedProductionSoustraitanceAuditRoute: typeof AuthenticatedProductionSoustraitanceAuditRoute
  AuthenticatedProductionTachesRoute: typeof AuthenticatedProductionTachesRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionAnalyseRoute: AuthenticatedProductionAnalyseRoute,
    AuthenticatedProductionConsommationRoute:
      AuthenticatedProductionConsommationRoute,
    AuthenticatedProductionPhasesRoute: AuthenticatedProductionPhasesRoute,
    AuthenticatedProductionRendementRoute:
      AuthenticatedProductionRendementRoute,
    AuthenticatedProductionSoustraitanceRoute:
      AuthenticatedProductionSoustraitanceRoute,
    AuthenticatedProductionSoustraitanceAuditRoute:
      AuthenticatedProductionSoustraitanceAuditRoute,
    AuthenticatedProductionTachesRoute: AuthenticatedProductionTachesRoute,
    AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedStocksRouteChildren {
  AuthenticatedStocksAnalyseRoute: typeof AuthenticatedStocksAnalyseRoute
  AuthenticatedStocksInventaireRoute: typeof AuthenticatedStocksInventaireRoute
  AuthenticatedStocksTransfertsRoute: typeof AuthenticatedStocksTransfertsRoute
  AuthenticatedStocksIndexRoute: typeof AuthenticatedStocksIndexRoute
}

const AuthenticatedStocksRouteChildren: AuthenticatedStocksRouteChildren = {
  AuthenticatedStocksAnalyseRoute: AuthenticatedStocksAnalyseRoute,
  AuthenticatedStocksInventaireRoute: AuthenticatedStocksInventaireRoute,
  AuthenticatedStocksTransfertsRoute: AuthenticatedStocksTransfertsRoute,
  AuthenticatedStocksIndexRoute: AuthenticatedStocksIndexRoute,
}

const AuthenticatedStocksRouteWithChildren =
  AuthenticatedStocksRoute._addFileChildren(AuthenticatedStocksRouteChildren)

interface AuthenticatedTransportRouteChildren {
  AuthenticatedTransportAnalyseRoute: typeof AuthenticatedTransportAnalyseRoute
  AuthenticatedTransportSuiviRoute: typeof AuthenticatedTransportSuiviRoute
  AuthenticatedTransportIndexRoute: typeof AuthenticatedTransportIndexRoute
}

const AuthenticatedTransportRouteChildren: AuthenticatedTransportRouteChildren =
  {
    AuthenticatedTransportAnalyseRoute: AuthenticatedTransportAnalyseRoute,
    AuthenticatedTransportSuiviRoute: AuthenticatedTransportSuiviRoute,
    AuthenticatedTransportIndexRoute: AuthenticatedTransportIndexRoute,
  }

const AuthenticatedTransportRouteWithChildren =
  AuthenticatedTransportRoute._addFileChildren(
    AuthenticatedTransportRouteChildren,
  )

interface AuthenticatedVentesRouteChildren {
  AuthenticatedVentesAnalyseRoute: typeof AuthenticatedVentesAnalyseRoute
  AuthenticatedVentesAvoirsRoute: typeof AuthenticatedVentesAvoirsRoute
  AuthenticatedVentesCommandesRoute: typeof AuthenticatedVentesCommandesRoute
  AuthenticatedVentesDevisRoute: typeof AuthenticatedVentesDevisRoute
  AuthenticatedVentesFacturesRoute: typeof AuthenticatedVentesFacturesRoute
  AuthenticatedVentesLivraisonsRoute: typeof AuthenticatedVentesLivraisonsRoute
  AuthenticatedVentesReglementsRoute: typeof AuthenticatedVentesReglementsRoute
  AuthenticatedVentesRetoursRoute: typeof AuthenticatedVentesRetoursRoute
  AuthenticatedVentesIndexRoute: typeof AuthenticatedVentesIndexRoute
}

const AuthenticatedVentesRouteChildren: AuthenticatedVentesRouteChildren = {
  AuthenticatedVentesAnalyseRoute: AuthenticatedVentesAnalyseRoute,
  AuthenticatedVentesAvoirsRoute: AuthenticatedVentesAvoirsRoute,
  AuthenticatedVentesCommandesRoute: AuthenticatedVentesCommandesRoute,
  AuthenticatedVentesDevisRoute: AuthenticatedVentesDevisRoute,
  AuthenticatedVentesFacturesRoute: AuthenticatedVentesFacturesRoute,
  AuthenticatedVentesLivraisonsRoute: AuthenticatedVentesLivraisonsRoute,
  AuthenticatedVentesReglementsRoute: AuthenticatedVentesReglementsRoute,
  AuthenticatedVentesRetoursRoute: AuthenticatedVentesRetoursRoute,
  AuthenticatedVentesIndexRoute: AuthenticatedVentesIndexRoute,
}

const AuthenticatedVentesRouteWithChildren =
  AuthenticatedVentesRoute._addFileChildren(AuthenticatedVentesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchatsRoute: typeof AuthenticatedAchatsRouteWithChildren
  AuthenticatedAlertesRoute: typeof AuthenticatedAlertesRoute
  AuthenticatedCaissesRoute: typeof AuthenticatedCaissesRouteWithChildren
  AuthenticatedComptabiliteRoute: typeof AuthenticatedComptabiliteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonneesRoute: typeof AuthenticatedDonneesRouteWithChildren
  AuthenticatedMaterielRoute: typeof AuthenticatedMaterielRouteWithChildren
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRouteWithChildren
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRouteWithChildren
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRouteWithChildren
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchatsRoute: AuthenticatedAchatsRouteWithChildren,
  AuthenticatedAlertesRoute: AuthenticatedAlertesRoute,
  AuthenticatedCaissesRoute: AuthenticatedCaissesRouteWithChildren,
  AuthenticatedComptabiliteRoute: AuthenticatedComptabiliteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonneesRoute: AuthenticatedDonneesRouteWithChildren,
  AuthenticatedMaterielRoute: AuthenticatedMaterielRouteWithChildren,
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRouteWithChildren,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedStocksRoute: AuthenticatedStocksRouteWithChildren,
  AuthenticatedTransportRoute: AuthenticatedTransportRouteWithChildren,
  AuthenticatedVentesRoute: AuthenticatedVentesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
